//
//  SampleFSMActor.h
//  SampleVisualFSM_01
//
//  Created by Simon on 2/28/15.
//  Copyright (c) 2015 P9SOFT. All rights reserved.
//
//  Licensed under the MIT license.

#import "P9FSMActor.h"



#define FSM_FILEID_SAMPLE_01   1

//////////////////////////////////////////////////////////////////////////////////////
// The folloing definitions were generated by Visio using 'ExportToXML.cls' script.

#define FSM_SHT_START @"Sht_Start"
#define FSM_SHT_SUBLOGIC @"Sht_SubLogic"

#define FSM_ACT_ENTERINITSTATE 101
#define FSM_ACT_EXITINITSTATE 102
#define FSM_ARC_RUNSUBSTATE 101
#define FSM_ACT_ENTERTERMINATE 103
#define FSM_ARC_GOTOTERMINATE 102
#define FSM_ARC_START 104
#define FSM_BRANCH_ISTHISGOOD @"IsThisGood"
#define FSM_ACT_STARTSUBLOGIC 104
#define FSM_ARC_GONEXTSTEP 105
#define FSM_ACT_ENTERBAD 105
#define FSM_ACT_ENTERGOOD 106
#define FSM_ARC_NO 106
#define FSM_ARC_YES 107

//
//////////////////////////////////////////////////////////////////////////////////////


@protocol SampleFSMActorDelegate <NSObject>

// Sht_Start
-(void) OnEnterInitState;
-(void) OnExitInitState;
-(void) OnEnterTerminate;

// Sht_SubLogic
-(void) OnEnterStartSubLogic;
-(void) OnEnterGood;
-(void) OnEnterBad;

// branch
-(bool) OnBranchIsThisGood;

@end



@interface SampleFSMActor : P9FSMActor

@property (nonatomic, weak) id<SampleFSMActorDelegate> delegate;

@end
